/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes/route'
import { Route as AuthenticatedNotesNewImport } from './routes/_authenticated/notes/new'
import { Route as AuthenticatedNotesNoteIdImport } from './routes/_authenticated/notes/$noteId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const AuthenticatedNotesIndexLazyImport = createFileRoute(
  '/_authenticated/notes/',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
)

const AuthenticatedNotesRouteRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedNotesIndexLazyRoute =
  AuthenticatedNotesIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/notes/index.lazy').then((d) => d.Route),
  )

const AuthenticatedNotesNewRoute = AuthenticatedNotesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedNotesRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/notes/new.lazy').then((d) => d.Route),
)

const AuthenticatedNotesNoteIdRoute = AuthenticatedNotesNoteIdImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AuthenticatedNotesRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/notes/$noteId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdImport
      parentRoute: typeof AuthenticatedNotesRouteImport
    }
    '/_authenticated/notes/new': {
      id: '/_authenticated/notes/new'
      path: '/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthenticatedNotesNewImport
      parentRoute: typeof AuthenticatedNotesRouteImport
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexLazyImport
      parentRoute: typeof AuthenticatedNotesRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedNotesRouteRouteChildren {
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedNotesIndexLazyRoute: typeof AuthenticatedNotesIndexLazyRoute
}

const AuthenticatedNotesRouteRouteChildren: AuthenticatedNotesRouteRouteChildren =
  {
    AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
    AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
    AuthenticatedNotesIndexLazyRoute: AuthenticatedNotesIndexLazyRoute,
  }

const AuthenticatedNotesRouteRouteWithChildren =
  AuthenticatedNotesRouteRoute._addFileChildren(
    AuthenticatedNotesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedNotesRouteRoute: typeof AuthenticatedNotesRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotesRouteRoute: AuthenticatedNotesRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/notes': typeof AuthenticatedNotesRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes/': typeof AuthenticatedNotesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes': typeof AuthenticatedNotesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/notes/new': typeof AuthenticatedNotesNewRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/notes'
    | '/settings'
    | '/'
    | '/notes/$noteId'
    | '/notes/new'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/settings' | '/' | '/notes/$noteId' | '/notes/new' | '/notes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/notes'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/notes/new'
    | '/_authenticated/notes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/about"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/notes",
        "/_authenticated/settings",
        "/_authenticated/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_authenticated/notes": {
      "filePath": "_authenticated/notes/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/notes/$noteId",
        "/_authenticated/notes/new",
        "/_authenticated/notes/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/notes/$noteId": {
      "filePath": "_authenticated/notes/$noteId.tsx",
      "parent": "/_authenticated/notes"
    },
    "/_authenticated/notes/new": {
      "filePath": "_authenticated/notes/new.tsx",
      "parent": "/_authenticated/notes"
    },
    "/_authenticated/notes/": {
      "filePath": "_authenticated/notes/index.lazy.tsx",
      "parent": "/_authenticated/notes"
    }
  }
}
ROUTE_MANIFEST_END */
