/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes/route'
import { Route as AuthenticatedNotesCreateRouteImport } from './routes/_authenticated/notes/create/route'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const AuthenticatedAccountLazyImport = createFileRoute(
  '/_authenticated/account',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)

const AuthenticatedAccountLazyRoute = AuthenticatedAccountLazyImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/account.lazy').then((d) => d.Route),
)

const AuthenticatedNotesRouteRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/notes/route.lazy').then((d) => d.Route),
)

const AuthenticatedNotesCreateRouteRoute =
  AuthenticatedNotesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedNotesRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/notes/create/route.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/notes/create': {
      id: '/_authenticated/notes/create'
      path: '/create'
      fullPath: '/notes/create'
      preLoaderRoute: typeof AuthenticatedNotesCreateRouteImport
      parentRoute: typeof AuthenticatedNotesRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedNotesRouteRouteChildren {
  AuthenticatedNotesCreateRouteRoute: typeof AuthenticatedNotesCreateRouteRoute
}

const AuthenticatedNotesRouteRouteChildren: AuthenticatedNotesRouteRouteChildren =
  {
    AuthenticatedNotesCreateRouteRoute: AuthenticatedNotesCreateRouteRoute,
  }

const AuthenticatedNotesRouteRouteWithChildren =
  AuthenticatedNotesRouteRoute._addFileChildren(
    AuthenticatedNotesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedNotesRouteRoute: typeof AuthenticatedNotesRouteRouteWithChildren
  AuthenticatedAccountLazyRoute: typeof AuthenticatedAccountLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotesRouteRoute: AuthenticatedNotesRouteRouteWithChildren,
  AuthenticatedAccountLazyRoute: AuthenticatedAccountLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/notes': typeof AuthenticatedNotesRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/create': typeof AuthenticatedNotesCreateRouteRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/notes': typeof AuthenticatedNotesRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/notes/create': typeof AuthenticatedNotesCreateRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/notes/create': typeof AuthenticatedNotesCreateRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/notes' | '/account' | '/' | '/notes/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/notes' | '/account' | '/' | '/notes/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/notes'
    | '/_authenticated/account'
    | '/_authenticated/'
    | '/_authenticated/notes/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/about"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/notes",
        "/_authenticated/account",
        "/_authenticated/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_authenticated/notes": {
      "filePath": "_authenticated/notes/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/notes/create"
      ]
    },
    "/_authenticated/account": {
      "filePath": "_authenticated/account.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/notes/create": {
      "filePath": "_authenticated/notes/create/route.tsx",
      "parent": "/_authenticated/notes"
    }
  }
}
ROUTE_MANIFEST_END */
